name: Maven and Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build WAR package
        run: mvn --batch-mode clean package -DskipTests

      - name: Set VERSION environment variable
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/student-service:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/student-service:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/student-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-service:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-service:latest
